SIZE = WIDTH, HEIGHT = 1200, 1000


NUM_OF_POINTS = 24
BAR_WIDTH = 150
MID_HEIGHT = 200
COLOR_ONE = (110, 67, 24)
COLOR_TWO = (244, 226, 198)




RIGHT_BOARD_MIN_X = (WIDTH-BAR_WIDTH)/2 + BAR_WIDTH
LEFT_BOARD_MAX_X = (WIDTH-BAR_WIDTH)/2
TOP_ROW_MAX_HEIGHT = (HEIGHT-MID_HEIGHT)/2
TOP_ROW_MIN_HEIGHT = (HEIGHT-MID_HEIGHT)/2 + MID_HEIGHT

DICE_HEIGHT = 50
DICE_WIDTH = 50
DICE_Y = ((MID_HEIGHT/2) - (DICE_HEIGHT/2)) + TOP_ROW_MAX_HEIGHT
DICE_1_X = ((WIDTH-BAR_WIDTH)/2)/2 - (DICE_HEIGHT/2)
DICE_2_X = DICE_1_X + DICE_WIDTH
DICE_3_X = (((WIDTH-BAR_WIDTH)/2)/2 + RIGHT_BOARD_MIN_X) - (DICE_HEIGHT/2)
DICE_4_X = DICE_3_X + DICE_WIDTH